### ISSUE TITLE
FR10: Report User

### ISSUE THREAD

**Issue by BetOnJeanette** [WSU-4110/LAN-Party-App#10]
| FR10: Blacklist/rate users |
|---|
| **Goal**: Party hosts can either prevent certain gamers from finding or registering for future events, or rate players based on interactions |
| **Stakeholders**: Party hosts |
|Users may find that other users who attend their parties may cause issues. In order to prevent future problems at their parties, these users can decide to report a user to the developers of the app for further investigation. |
| **Origin**: Party hosts do not want to actively worry if their party is going to be hampered by players who they know cause problems. This is a simple way to reduce the issue. |
| **Version**: 1.2 |
| **Date**: 11/7/2020 |
| **Priority**: 3 |

**Comment by ga2599** [comment]
thinking of putting an array of blocked users for each user, front end might want to toggle "show blocked users" so that just in case they are in a party they can see them

**Comment by ga2599** [comment]
one thing that we need to do is delete a friendship if someone blocks a friend

**Comment by ga2599** [comment]
need to pop up a contact form and then email this over to all of our emails

**Comment by ga2599** [comment]
thanks, looks good
