### ISSUE TITLE
NFR6: Performance

### ISSUE THREAD

**Issue by BetOnJeanette** [WSU-4110/LAN-Party-App#21]
| NFR6: Performance |
|---|
| **Goal**: Our system will perform so that our users receive responses within 0.1 seconds with more than 60% accuracy. |
| **Stakeholders**: Users |
| We want to ensure that our app is fast enough so that people do not feel frustrated with the system. |
| **Origin**: This was discussed during a scrum meeting by all members. |
| **Version**: 1.1 |
| **Date**: 9/28/2020 |
| **Priority**: 2 |

**Comment by ThaddG** [comment]
I was waiting until the whole app is done for the semester to be sure that everything does actually run smoothly and not extremely slow. I can confidently say that there are no hiccups in our app now (for the features that are implemented).
