### ISSUE TITLE
FR16: Host A Party

### ISSUE THREAD

**Issue by BetOnJeanette** [WSU-4110/LAN-Party-App#22]
| FR16: Host A Party |
|---|
| **Goal**: Users can create LAN parties for others to attend |
| Users can create parties, including setting its locations, send invites |
| **Origin**: its the entire point of the application |
| **Version**: 1.0 |
| **Date**: 9/11/2020 |
| **Priority**: 1 |

**Comment by ga2599** [comment]
completed in sprint 1 refer to the old repo: https://github.com/WSU-4110/LAN-party-backend/issues/22
