### ISSUE TITLE
FR19: View Friend's List

### ISSUE THREAD

**Issue by BetOnJeanette** [WSU-4110/LAN-Party-App#25]
| FR19: View Friend's List |
|---|
| **Goal**: Users view all their friends that they have from the friends tab |
| Users will be able to view all their friends in a list |
| **Origin**: After Thursday's lab class meeting |
| **Version**: 1.0 |
| **Date**: 10/8/2020 |
| **Priority**: 1 |

**Comment by ga2599** [comment]
table is up, but that is about it for the moment. going to work on the skeleton next

**Comment by ga2599** [comment]
jarred taking this issue over
