### ISSUE TITLE
FR24 - About me on user page

### ISSUE THREAD

**Issue by codemonkeman** [WSU-4110/LAN-Party-App#31]
|FR24 - About me on user page|
|---|
|**Goal:** User should be able to view other users (public) accounts before adding them ad friends
**Stakeholders:** Users (Gamers)|
|**Description:** A user can clock on another users profile after either searching for it, or finding it otherwise from a list of party attendies or something similar. User will have the option to view public info on the user, request them as a friend, or block them. PROFILE WILL CONTAIN SELF-WRITTEN 'ABOUT ME' SECTION which is the real reason for this requirement. |
|**Origin:** During the 10/17 Scrum meeting we realized that this requirement hadn't been added earlier, we decided an "about me" section would be important if we had to push the "favorite games requirement back, and also will just help users figure out. |
|**Version:** 1.0|
|**Date:** 10/17/2020|
|**Priority:** 2|

**Comment by randallwestbrook** [comment]
Should not be a problem. Once this week calms down, I'll be able to get to work on it.

**Comment by randallwestbrook** [comment]
This
issue
is
no
more

**Comment by randallwestbrook** [comment]
Reopened to close officially with pull request.

**Comment by randallwestbrook** [comment]
merged and closed
