### ISSUE TITLE
FR1 - Find parties

### ISSUE THREAD

**Issue by ThaddG** [WSU-4110/LAN-Party-App#35]
|FR1.  Find parties|
|---|
| **Goal**: user interface will allow gamers to see upcoming events and register for them based on their location.|
| **Stakeholders**: Gamers / Event organizers|
| Gamers can look at the map and list interface for upcoming events, based on either their GPS location. Or based on a location they specify (they might be travelling for the event). The gamer should be able to also register for the event quickly when they find one they are interested in.|
| **Origin**: The entire point for the app is to bring gamers together so they can play, this is just our best idea in terms of user interface to facilitate it easily.|
| **Version**: 1.0 |
| **Date**: 09/11/2019 |
| **Priority**: 1 |

**Comment by codemonkeman** [comment]
Got the front end to grab the info from the database, get function works. Didn't understand environment variable and got hung up (because I didn't have one) for three days. Should be pretty easy to get it to query by a search term, or GPS position, that's the next step.

**Comment by codemonkeman** [comment]
This is basically done now, can't do search, but it's fine for now. Will do basic search for search user and try to apply that knowledge later.

**Comment by codemonkeman** [comment]
Got filtered search working, actually didn't take much code, I was making it WAY harder than it actually needed to be.
