### ISSUE TITLE
FR9 - Age Gate

### ISSUE THREAD

**Issue by ThaddG** [WSU-4110/LAN-Party-App#39]
| FR9:  Age Gate |
|---|
| Goal: Restrict the rights of 16 year olds and those who are younger to protect their safety and follow the law |
| **Stakeholders**: All |
| One must be 18 years old to host a party. One must be 16 years old to join the app. Host will have the ability to create events that restrict certain ages. For example, if this event serves alcohol then it will restrict the age groups. |
| **Origin**: James’ idea and needed if we are to have an app that brings people together in real person |
| **Version**: 1.2 |
| **Date**: 9/11/2020 |
| **Priority**: 3 |

**Comment by randallwestbrook** [comment]
*thumbs up*

**Comment by randallwestbrook** [comment]
form added for host to set minimum age in HostParty. after meeting tomorrow night, I will start working on a script for a popup that will ask user to confirm that they meet age requirement prior to joining.

**Comment by randallwestbrook** [comment]
Minimum age can be set from HostParty and seen in ViewParty. Once we've got a concrete way to join parties, I'll add the popup mentioned above.

**Comment by randallwestbrook** [comment]
officially finished. popup window asking member to verify that age meets requirement now active.
